/*
 * Agregar.java
 *
 * Created on 19 de diciembre de 2007, 3:13
 */

package agenda2;

import javax.swing.JOptionPane;

/**
 *
 * @author  Cristian Riffo Huez
 */
public class Agregar extends javax.swing.JFrame {
    
    String generoElegido;
    
    /** Creates new form Agregar */
    public Agregar() {
        initComponents();
        //centrar en el monitor
        this.setLocationRelativeTo(null);
   }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        genero = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        apellido = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        femenino = new javax.swing.JRadioButton();
        masculino = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        numeroFono = new javax.swing.JTextField();
        tipoFono = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jToggleButton1 = new javax.swing.JToggleButton();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Cooper Black", 1, 14));
        jLabel6.setText("Agenda Telef\u00f3nica");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jLabel1.setText("Nombre");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreActionPerformed(evt);
            }
        });

        jPanel1.add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 70, -1));

        jPanel1.add(apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 70, -1));

        jLabel2.setText("Apellido");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, -1, -1));

        jLabel3.setText("Genero");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        genero.add(femenino);
        femenino.setSelected(true);
        femenino.setText("Femenino");
        femenino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femeninoActionPerformed(evt);
            }
        });

        jPanel1.add(femenino, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        genero.add(masculino);
        masculino.setText("Masculino");
        masculino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masculinoActionPerformed(evt);
            }
        });

        jPanel1.add(masculino, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, -1, -1));

        jLabel4.setText("Tel\u00e9fono");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        jLabel5.setText("N\u00famero");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, -1, -1));

        jPanel1.add(numeroFono, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 60, -1));

        tipoFono.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "[Seleccione]", "Fijo", "Celular" }));
        jPanel1.add(tipoFono, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));

        jButton1.setText("Agregar Contacto");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 290, -1, -1));

        jToggleButton1.setText("Ir al Listado");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        jPanel1.add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 330, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 270, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
// TODO add your handling code here:
        //ir al listado y ocultar esta ventana
        new Listado().setVisible(true);
        Listado.mostrarContactos();
        this.setVisible(false);
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
// TODO add your handling code here:
        //Consultamos si ha llenado los datos
        if(nombre.getText().length()==0 || numeroFono.getText().length()==0){
            JOptionPane.showMessageDialog(null, "Complete el formulario", "Error!", 2);
        } else{
            //agregamos los datos a la agenda
            String[] datos={nombre.getText(), apellido.getText(), generoElegido, tipoFono.getSelectedItem().toString(), numeroFono.getText()};
            MiAgenda.agenda.add(datos);
            //Limpiamos formulario
            nombre.setText("");
            apellido.setText("");
            femenino.setSelected(true);
            masculino.setSelected(false);
            numeroFono.setText("");
            tipoFono.setSelectedIndex(0);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void masculinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masculinoActionPerformed
// TODO add your handling code here:
        generoElegido=masculino.getText();
    }//GEN-LAST:event_masculinoActionPerformed

    private void femeninoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femeninoActionPerformed
// TODO add your handling code here:
        generoElegido=femenino.getText();
    }//GEN-LAST:event_femeninoActionPerformed

    private void nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreActionPerformed
// TODO add your handling code here:
    }//GEN-LAST:event_nombreActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Agregar().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField apellido;
    private javax.swing.JRadioButton femenino;
    private javax.swing.ButtonGroup genero;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JRadioButton masculino;
    private javax.swing.JTextField nombre;
    private javax.swing.JTextField numeroFono;
    private javax.swing.JComboBox tipoFono;
    // End of variables declaration//GEN-END:variables
    
}
